"""initial

Revision ID: 2a0f09adf2d8
Revises: 640e1da505bf
Create Date: 2026-07-16 09:01:16.361268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a0f09adf2d8'
down_revision: Union[str, Sequence[str], None] = '640e1da505bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('cars', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('cars', sa.Column('horsepower', sa.Integer(), nullable=True))
    op.add_column('cars', sa.Column('acceleration', sa.Float(), nullable=True))
    op.add_column('cars', sa.Column('drive', sa.String(length=30), nullable=True))
    op.add_column('cars', sa.Column('safety', sa.Float(), nullable=True))
    op.add_column('cars', sa.Column('comfort', sa.Float(), nullable=True))
    op.add_column('cars', sa.Column('reliability', sa.Float(), nullable=True))
    op.add_column('cars', sa.Column('maintenance', sa.Float(), nullable=True))
    op.add_column('cars', sa.Column('vin', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('cover_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'cover_url')
    op.drop_column('cars', 'vin')
    op.drop_column('cars', 'maintenance')
    op.drop_column('cars', 'reliability')
    op.drop_column('cars', 'comfort')
    op.drop_column('cars', 'safety')
    op.drop_column('cars', 'drive')
    op.drop_column('cars', 'acceleration')
    op.drop_column('cars', 'horsepower')
    op.drop_column('cars', 'longitude')
    op.drop_column('cars', 'latitude')
    # ### end Alembic commands ###
