"""final migrate

Revision ID: 572c030b9413
Revises: f0f31d3dd336
Create Date: 2026-07-16 20:52:16.979397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '572c030b9413'
down_revision: Union[str, Sequence[str], None] = 'f0f31d3dd336'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ownership_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vin', sa.String(length=50), nullable=False),
    sa.Column('owner_count', sa.Integer(), nullable=False),
    sa.Column('accidents_count', sa.Integer(), nullable=False),
    sa.Column('theft_status', sa.String(length=50), nullable=False),
    sa.Column('loan_status', sa.String(length=50), nullable=False),
    sa.Column('import_history', sa.Text(), nullable=True),
    sa.Column('mileage_history', sa.JSON(), nullable=True),
    sa.Column('inspection_records', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ownership_history_id'), 'ownership_history', ['id'], unique=False)
    op.create_index(op.f('ix_ownership_history_vin'), 'ownership_history', ['vin'], unique=True)
    op.create_table('community_forum_topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_forum_topics_author_id'), 'community_forum_topics', ['author_id'], unique=False)
    op.create_index(op.f('ix_community_forum_topics_brand'), 'community_forum_topics', ['brand'], unique=False)
    op.create_index(op.f('ix_community_forum_topics_id'), 'community_forum_topics', ['id'], unique=False)
    op.create_index(op.f('ix_community_forum_topics_model'), 'community_forum_topics', ['model'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('user_followers',
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followed_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['followed_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('follower_id', 'followed_id')
    )
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('booking_type', sa.String(length=50), nullable=False),
    sa.Column('appointment_datetime', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_buyer_id'), 'bookings', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_bookings_car_id'), 'bookings', ['car_id'], unique=False)
    op.create_index(op.f('ix_bookings_id'), 'bookings', ['id'], unique=False)
    op.create_table('car_battles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car1_id', sa.Integer(), nullable=False),
    sa.Column('car2_id', sa.Integer(), nullable=False),
    sa.Column('winner_id', sa.Integer(), nullable=True),
    sa.Column('ai_verdict', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['car1_id'], ['cars.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['car2_id'], ['cars.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['winner_id'], ['cars.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_car_battles_car1_id'), 'car_battles', ['car1_id'], unique=False)
    op.create_index(op.f('ix_car_battles_car2_id'), 'car_battles', ['car2_id'], unique=False)
    op.create_index(op.f('ix_car_battles_id'), 'car_battles', ['id'], unique=False)
    op.create_table('community_forum_replies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['community_forum_topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_forum_replies_author_id'), 'community_forum_replies', ['author_id'], unique=False)
    op.create_index(op.f('ix_community_forum_replies_id'), 'community_forum_replies', ['id'], unique=False)
    op.create_index(op.f('ix_community_forum_replies_topic_id'), 'community_forum_replies', ['topic_id'], unique=False)
    op.create_table('dream_garage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dream_garage_car_id'), 'dream_garage', ['car_id'], unique=False)
    op.create_index(op.f('ix_dream_garage_id'), 'dream_garage', ['id'], unique=False)
    op.create_index(op.f('ix_dream_garage_user_id'), 'dream_garage', ['user_id'], unique=False)
    op.create_table('price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('changed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_history_car_id'), 'price_history', ['car_id'], unique=False)
    op.create_index(op.f('ix_price_history_id'), 'price_history', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_price_history_id'), table_name='price_history')
    op.drop_index(op.f('ix_price_history_car_id'), table_name='price_history')
    op.drop_table('price_history')
    op.drop_index(op.f('ix_dream_garage_user_id'), table_name='dream_garage')
    op.drop_index(op.f('ix_dream_garage_id'), table_name='dream_garage')
    op.drop_index(op.f('ix_dream_garage_car_id'), table_name='dream_garage')
    op.drop_table('dream_garage')
    op.drop_index(op.f('ix_community_forum_replies_topic_id'), table_name='community_forum_replies')
    op.drop_index(op.f('ix_community_forum_replies_id'), table_name='community_forum_replies')
    op.drop_index(op.f('ix_community_forum_replies_author_id'), table_name='community_forum_replies')
    op.drop_table('community_forum_replies')
    op.drop_index(op.f('ix_car_battles_id'), table_name='car_battles')
    op.drop_index(op.f('ix_car_battles_car2_id'), table_name='car_battles')
    op.drop_index(op.f('ix_car_battles_car1_id'), table_name='car_battles')
    op.drop_table('car_battles')
    op.drop_index(op.f('ix_bookings_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_car_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_buyer_id'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_table('user_followers')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_community_forum_topics_model'), table_name='community_forum_topics')
    op.drop_index(op.f('ix_community_forum_topics_id'), table_name='community_forum_topics')
    op.drop_index(op.f('ix_community_forum_topics_brand'), table_name='community_forum_topics')
    op.drop_index(op.f('ix_community_forum_topics_author_id'), table_name='community_forum_topics')
    op.drop_table('community_forum_topics')
    op.drop_index(op.f('ix_ownership_history_vin'), table_name='ownership_history')
    op.drop_index(op.f('ix_ownership_history_id'), table_name='ownership_history')
    op.drop_table('ownership_history')
    # ### end Alembic commands ###
